-- Create store_news table for scraping snapshots
create table if not exists public.store_news (
  id bigint generated by default as identity primary key,
  store_id bigint references public.store_management(id) on delete cascade not null,
  visitor_review_count int default 0,
  blog_review_count int default 0,
  news_content jsonb default '[]'::jsonb,
  reviews_content jsonb default '[]'::jsonb,
  phone text,
  address text,
  extracted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.store_news enable row level security;

-- Policies
create policy "Users can view their own store news"
on public.store_news for select
to authenticated
using (
  exists (
    select 1 from public.store_management
    where store_management.id = store_news.store_id
    and store_management.user_id = auth.uid()
  )
);

-- Allow cron/service role to insert (or authenticated users if triggering manually)
create policy "Users can insert their own store news"
on public.store_news for insert
to authenticated
with check (
  exists (
    select 1 from public.store_management
    where store_management.id = store_news.store_id
    and store_management.user_id = auth.uid()
  )
);
